//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUniverseMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        public int BattleID { get; set; }
        public int HeroID { get; set; }
        public int VillainID { get; set; }
    
        public virtual Hero Hero { get; set; }
        public virtual Villain Villain { get; set; }
    }
}
