//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCUniverseMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nemesi
    {
        public int NemesisID { get; set; }
        public string NemesisName { get; set; }
        public bool InJail { get; set; }
        public int NumberOfHenchmen { get; set; }
        public int HeroID { get; set; }
    
        public virtual Hero Hero { get; set; }
    }
}
